# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enterprise_computer_use/objects/computer_use_message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'enterprise_computer_use/objects/computer_use_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from enterprise_computer_use.objects import computer_use_side_channel_message_pb2 as enterprise__computer__use_dot_objects_dot_computer__use__side__channel__message__pb2
from enterprise_computer_use.objects import computer_use_empty_message_pb2 as enterprise__computer__use_dot_objects_dot_computer__use__empty__message__pb2
from enterprise_computer_use.objects import computer_use_data_message_pb2 as enterprise__computer__use_dot_objects_dot_computer__use__data__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:enterprise_computer_use/objects/computer_use_message.proto\x12\x14\x63omputer_use_objects\x1aGenterprise_computer_use/objects/computer_use_side_channel_message.proto\x1a@enterprise_computer_use/objects/computer_use_empty_message.proto\x1a?enterprise_computer_use/objects/computer_use_data_message.proto\"@\n\x1d\x43omputerUseMessageHeaderProto\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xc7\x02\n\x17\x43omputerUseMessageProto\x12\x43\n\x06header\x18\x01 \x01(\x0b\x32\x33.computer_use_objects.ComputerUseMessageHeaderProto\x12\x46\n\x08\x65mptyMsg\x18\x02 \x01(\x0b\x32\x32.computer_use_objects.ComputerUseEmptyMessageProtoH\x00\x12R\n\x0esideChannelMsg\x18\x03 \x01(\x0b\x32\x38.computer_use_objects.ComputerUseSideChannelMessageProtoH\x00\x12\x44\n\x07\x64\x61taMsg\x18\x04 \x01(\x0b\x32\x31.computer_use_objects.ComputerUseDataMessageProtoH\x00\x42\x05\n\x03msg*?\n\x1b\x43omputerUseMessageTypeProto\x12\t\n\x05\x45MPTY\x10\x00\x12\x0b\n\x07\x43HANNEL\x10\x01\x12\x08\n\x04\x44\x41TA\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enterprise_computer_use.objects.computer_use_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPUTERUSEMESSAGETYPEPROTO']._serialized_start=684
  _globals['_COMPUTERUSEMESSAGETYPEPROTO']._serialized_end=747
  _globals['_COMPUTERUSEMESSAGEHEADERPROTO']._serialized_start=288
  _globals['_COMPUTERUSEMESSAGEHEADERPROTO']._serialized_end=352
  _globals['_COMPUTERUSEMESSAGEPROTO']._serialized_start=355
  _globals['_COMPUTERUSEMESSAGEPROTO']._serialized_end=682
# @@protoc_insertion_point(module_scope)
