# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enterprise_computer_use/objects/computer_use.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'enterprise_computer_use/objects/computer_use.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from enterprise_computer_use.objects import computer_use_message_pb2 as enterprise__computer__use_dot_objects_dot_computer__use__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2enterprise_computer_use/objects/computer_use.proto\x12\x14\x63omputer_use_objects\x1a:enterprise_computer_use/objects/computer_use_message.proto2\x9f\x06\n\x10\x43omputerUseProto\x12\x66\n\x04step\x12-.computer_use_objects.ComputerUseMessageProto\x1a-.computer_use_objects.ComputerUseMessageProto\"\x00\x12g\n\x05reset\x12-.computer_use_objects.ComputerUseMessageProto\x1a-.computer_use_objects.ComputerUseMessageProto\"\x00\x12g\n\x05\x63lose\x12-.computer_use_objects.ComputerUseMessageProto\x1a-.computer_use_objects.ComputerUseMessageProto\"\x00\x12s\n\x11observation_space\x12-.computer_use_objects.ComputerUseMessageProto\x1a-.computer_use_objects.ComputerUseMessageProto\"\x00\x12n\n\x0c\x61\x63tion_space\x12-.computer_use_objects.ComputerUseMessageProto\x1a-.computer_use_objects.ComputerUseMessageProto\"\x00\x12s\n\x11side_channel_send\x12-.computer_use_objects.ComputerUseMessageProto\x1a-.computer_use_objects.ComputerUseMessageProto\"\x00\x12w\n\x13side_channel_stream\x12-.computer_use_objects.ComputerUseMessageProto\x1a-.computer_use_objects.ComputerUseMessageProto\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enterprise_computer_use.objects.computer_use_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPUTERUSEPROTO']._serialized_start=137
  _globals['_COMPUTERUSEPROTO']._serialized_end=936
# @@protoc_insertion_point(module_scope)
