# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from enterprise_computer_use.objects import computer_use_message_pb2 as enterprise__computer__use_dot_objects_dot_computer__use__message__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in enterprise_computer_use/objects/computer_use_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputerUseProtoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.step = channel.unary_unary(
                '/computer_use_objects.ComputerUseProto/step',
                request_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
                response_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                _registered_method=True)
        self.reset = channel.unary_unary(
                '/computer_use_objects.ComputerUseProto/reset',
                request_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
                response_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                _registered_method=True)
        self.close = channel.unary_unary(
                '/computer_use_objects.ComputerUseProto/close',
                request_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
                response_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                _registered_method=True)
        self.observation_space = channel.unary_unary(
                '/computer_use_objects.ComputerUseProto/observation_space',
                request_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
                response_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                _registered_method=True)
        self.action_space = channel.unary_unary(
                '/computer_use_objects.ComputerUseProto/action_space',
                request_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
                response_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                _registered_method=True)
        self.side_channel_send = channel.unary_unary(
                '/computer_use_objects.ComputerUseProto/side_channel_send',
                request_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
                response_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                _registered_method=True)
        self.side_channel_stream = channel.unary_stream(
                '/computer_use_objects.ComputerUseProto/side_channel_stream',
                request_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
                response_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                _registered_method=True)


class ComputerUseProtoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def observation_space(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def action_space(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def side_channel_send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def side_channel_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputerUseProtoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'step': grpc.unary_unary_rpc_method_handler(
                    servicer.step,
                    request_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                    response_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            ),
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                    response_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            ),
            'close': grpc.unary_unary_rpc_method_handler(
                    servicer.close,
                    request_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                    response_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            ),
            'observation_space': grpc.unary_unary_rpc_method_handler(
                    servicer.observation_space,
                    request_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                    response_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            ),
            'action_space': grpc.unary_unary_rpc_method_handler(
                    servicer.action_space,
                    request_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                    response_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            ),
            'side_channel_send': grpc.unary_unary_rpc_method_handler(
                    servicer.side_channel_send,
                    request_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                    response_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            ),
            'side_channel_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.side_channel_stream,
                    request_deserializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
                    response_serializer=enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'computer_use_objects.ComputerUseProto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('computer_use_objects.ComputerUseProto', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputerUseProto(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computer_use_objects.ComputerUseProto/step',
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computer_use_objects.ComputerUseProto/reset',
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computer_use_objects.ComputerUseProto/close',
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def observation_space(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computer_use_objects.ComputerUseProto/observation_space',
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def action_space(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computer_use_objects.ComputerUseProto/action_space',
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def side_channel_send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computer_use_objects.ComputerUseProto/side_channel_send',
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def side_channel_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/computer_use_objects.ComputerUseProto/side_channel_stream',
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.SerializeToString,
            enterprise__computer__use_dot_objects_dot_computer__use__message__pb2.ComputerUseMessageProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
