@backendBaseUrl = http://localhost:8010/api/v1
###
# @name login
POST {{backendBaseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "shakir",
    "password": "shakir123"
}

###
@authToken = {{login.response.body.access_token}}

###
# @name getUsers
GET {{backendBaseUrl}}/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name getFiles
GET {{backendBaseUrl}}/files/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name uploadFile
POST {{backendBaseUrl}}/files/upload/ HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="request.rest"
Content-Type: text/plain

< ./request.rest
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# @name getFileById
GET {{backendBaseUrl}}/files/cee387d1-c4f5-4dbe-84d6-f61bdd2780b4/ HTTP/1.1
Authorization: Bearer {{authToken}}

###
# @name deleteFile
DELETE {{backendBaseUrl}}/files/cee387d1-c4f5-4dbe-84d6-f61bdd2780b4 HTTP/1.1
Authorization: Bearer {{authToken}}


### CHAT ENDPOINTS ###

###
# @name createChat
POST {{backendBaseUrl}}/chats/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "initial_message": "Hello, I need help analyzing some data",
    "initial_role": "user"
}

###
# @name listUserChats
GET {{backendBaseUrl}}/chats/ HTTP/1.1
Authorization: Bearer {{authToken}}

###
# @name getChatWithHistory
GET {{backendBaseUrl}}/chats/b5c3b2aa-0945-4ee8-9d17-0ffe388d3529 HTTP/1.1
Authorization: Bearer {{authToken}}

###
# @name addMessageToChat
POST {{backendBaseUrl}}/chats/b5c3b2aa-0945-4ee8-9d17-0ffe388d3529/history HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "role": "user",
    "message": "Can you open excel files?",
    "extra_data": {}
}

###
# @name deleteChat
DELETE {{backendBaseUrl}}/chats/b5c3b2aa-0945-4ee8-9d17-0ffe388d3529 HTTP/1.1
Authorization: Bearer {{authToken}}