[tool.pyright]
venvPath = "."
venv = ".venv"
useLibraryCodeForTypes = false
exclude = ["**/objects"]  # Exclude all objects directories

[tool.pytest.ini_options]
pythonpath = "."
asyncio_mode = "auto"
