extend-exclude = [
    ".venv",
    "enterprise_computer_use/objects/**/*"  # Exclude all files in objects directory
]

# Set the line length at root level
line-length = 80

[format]
docstring-code-format = true

[lint]
select = [
    "A",
    "ASYNC",
    "B",
    "E",
    "F",
    "I",
    "PIE",
    "RUF200",
    "T20",
    "UP",
    "W",
]
ignore = ["E501", "ASYNC230"]

[lint.isort]
combine-as-imports = true
