name: Build and Push Backend Docker Image
# This GitHub Actions workflow builds and pushes a Docker image for the backend service
# of the Claude Computer Use project. It triggers on pushes to the main branch
# and only when files in the backend, deployment/cloud-k8s, or .github/workflows directories are changed.
# The workflow logs into Docker Hub, builds the Docker image using the Dockerfile in the backend directory,
# and then pushes the image to Docker Hub with the commit SHA as the tag.
# The image is tagged with the format: fattanishakir/claude-computer-use-backend:<commit-sha>.
# The commit SHA is set as an environment variable for use in the build and push steps.
# The workflow uses the latest version of Ubuntu as the runner environment.
# The Docker Hub credentials are stored as secrets in the GitHub repository.
# The workflow is designed to ensure that the backend service is always up-to-date with the latest code changes.

on:
  push:
    branches:
      - main # or your desired branch
    paths:
      - "backend/**"
      - "deployment/cloud-k8s/**"
      - ".github/workflows/backend-publish.yml"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Commit ID
        run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build Docker Main Image
        run: |
          docker build -t fattanishakir/claude-computer-use-backend:$GITHUB_SHA ./backend

      - name: Push Docker Main Image
        run: |
          docker push fattanishakir/claude-computer-use-backend:$GITHUB_SHA

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}
